### ISSUE TITLE
 Organize images in subfolder(s)

### ISSUE THREAD

**Issue by WimTeuling** [Pureum309/MDIA2003_lab#12]
Manage all your image files in subfolders. It is bad practice to allow all your images to be saved in the root of your project folder.

Ideally create an img folder for content images, and a theme folder in which you put all non-content images.

css
img
theme

Exceptions:
favicon, app icons, etcetera. Refer to the html5 boilerplate.

**Comment by Pureum309** [comment]
Moved all css file into css folder, also all images in imgs file.
