### ISSUE TITLE
ID selectors used.

### ISSUE THREAD

**Issue by WimTeuling** [Pureum309/MDIA2003_lab#15]
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L21
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L78
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L83
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L98
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L108

Check that ID selectors are used only for fragment identifiers or javascript hooks. ID selectors are best avoided aside from these two cases. Use classes only otherwise.

**Comment by KayceeNguyen** [comment]
Fixed ID selectors used. #15!
