### ISSUE TITLE
Selector labels are numbered

### ISSUE THREAD

**Issue by WimTeuling** [Pureum309/MDIA2003_lab#18]
Selector labels should avoid numbering (unless they are used as utility classes such as for a reusable css grid where the numbers are meaningful). Numbering your selector labels is bad practice, and ties your CSS code to the underlying html structure. Not very reusable or meaningful (semantic).

https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L33
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L34
..and others in the menu

https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L21
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L84
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L108
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L117
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L124
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L125
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L130
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L137
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L138

...and so on

https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L178

https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L186
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L210
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L234
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L272
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L275
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L278

...and so on
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L335)

https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L565
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L602
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L633
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L660

**Comment by KayceeNguyen** [comment]
Fixed by Sarah
