### ISSUE TITLE
 Avoid stylistic tags used for visual theming: main nav buttons

### ISSUE THREAD

**Issue by WimTeuling** [Pureum309/MDIA2003_lab#19]
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L33
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L40
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L47
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L54
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L61

Keep styling and content strictly separated when creating the html structure. This should be assigned as a background style.

**Comment by KayceeNguyen** [comment]
Fixed: change header_abc class name to hd_abc.
