### ISSUE TITLE
remove tag that indicates workflow by developers

### ISSUE THREAD

**Issue by WimTeuling** [Pureum309/MDIA2003_lab#22]
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L21

Replace with a comment:

**Comment by KayceeNguyen** [comment]
I added this tag in order to separate my work with my team-mate's work, cause when I put HTML {} in the CSS, it overwrote on both of our work. The only and fastest option I could think of is to put the first half code into a section tag like this.
