### ISSUE TITLE
Section in footer: use header tag instead

### ISSUE THREAD

**Issue by WimTeuling** [Pureum309/MDIA2003_lab#36]
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L540

I would argue that it is probably a better idea to use a <header> tag here. Or remove, and assign as a regular footer column that happens to span the full width.

**Comment by Pureum309** [comment]
Changed with class name
