### ISSUE TITLE
Define and assign heading class and change to h3

### ISSUE THREAD

**Issue by WimTeuling** [Pureum309/MDIA2003_lab#37]
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L547

This is quite an important heading - use h3 instead.
Also assign a heading class.
```

<h3 class="heading footer__column__heading inverted">
    Pewee Herman
</h3>
```

**Comment by Pureum309** [comment]
changed to <h3>
