### ISSUE TITLE
Use a heading tag if you intend to assign a heading tag

### ISSUE THREAD

**Issue by WimTeuling** [Pureum309/MDIA2003_lab#38]
https://github.com/Pureum309/MDIA2003_lab/blob/4cb731c5e68d0622d6eae5b43bc8d355cc15e75c/index.html#L565

Do not invent a h1 class. This is a heading, and it is important for the document outline structure to assign an actual heading tag.

I would argue it is on the same level as the previous one.

```
<h3 class="heading footer__column__heading inverted">
    About Us
</h3>
```
But feel free to use an h4 instead, and perhaps a different classname for this heading.

**Comment by Pureum309** [comment]
changed with other class name
